<script setup>
</script>
<template>
   
    <section class="video">
        <div class="video-text">
            <h1 class="header">Fangende tekst</h1>
            <h2 class="heading">Ladida tekst tekst</h2>
            <div class="cases-btn">
                <a href="#">Kontakt os</a>
            </div>
        </div>
        <div class="overlay"></div>
        <div class="video-mpg">
            <video src="../../assets/video/background_wcolor.mp4" loop autoplay></video>
        </div> 
    </section>
</template>

<style lang="scss" scoped>
@import "../frontpage/VideoSection.scss";
@import "../../assets/styling/variables/colors";
@import "../../assets/styling/variables/fonts";

</style>