

<template>
   
    <section class="video">
        <div class="video-container">
            <video src="../../assets/video/background_wcolor.mp4" loop autoplay ></video>
        </div> 
        <div class="video-text">
            <h1 class="main-header">Geodata er med til at give indsigt</h1>
            <h2 class="heading">Leverandør indenfor GIS, OIS & CAD løsninger</h2>
            <a class="contact-btn" href="/kontakt">Kontakt os</a>
        </div>
        <div class="overlay"></div>
    </section>
</template>

<style lang="scss" scoped>
    @import "../frontpage/VideoSection.scss";
    @import "../../assets/styling/variables/colors";
    @import "../../assets/styling/variables/fonts";
</style>